# Generated by Django 4.1.7 on 2023-03-14 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('language', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('date_published', models.DateField()),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('format', models.CharField(blank=True, max_length=75)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_api.author')),
            ],
        ),
    ]
